name: CI / Bump version
on:
  pull_request:
    branches:
      - dev
    types: [closed]
jobs:
  bump:
    if: github.event.pull_request.merged == true
    name: "Bump Version"
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v3"
        with:
          token: ${{ secrets.TOKEN }}
          fetch-depth: 0
      - name: "Bump version"
        uses: ./
